# Generated by Django 3.2.7 on 2021-10-04 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=50)),
                ('upliner', models.CharField(default='', max_length=50)),
                ('uplinerphone', models.IntegerField(default=0)),
                ('Maelezo', models.TextField()),
                ('profilemake', models.CharField(blank=True, default='', max_length=100)),
                ('backofice', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('region', models.CharField(default='', max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('debt', models.IntegerField(default=0)),
                ('firstgenb', models.IntegerField(default=0)),
                ('secondgenb', models.IntegerField(default=0)),
                ('thirdgenb', models.IntegerField(default=0)),
                ('fouthgenb', models.IntegerField(default=0)),
                ('fifthgenb', models.IntegerField(default=0)),
                ('firstmthb', models.IntegerField(default=0)),
                ('city', models.CharField(default='', max_length=100)),
                ('secondmthb', models.IntegerField(default=0)),
                ('thirdmthb', models.IntegerField(default=0)),
                ('fouthmthb', models.IntegerField(default=0)),
                ('fifthmthb', models.IntegerField(default=0)),
                ('sixthmthb', models.IntegerField(default=0)),
                ('totalb', models.IntegerField(default=0)),
                ('accountdescription', models.TextField(default='')),
                ('firstgenr', models.IntegerField(default=0)),
                ('secondgenr', models.IntegerField(default=0)),
                ('thirdgenr', models.IntegerField(default=0)),
                ('fouthgenr', models.IntegerField(default=0)),
                ('fifthgenr', models.IntegerField(default=0)),
                ('firstmthr', models.IntegerField(default=0)),
                ('secondmthr', models.IntegerField(default=0)),
                ('thirdmthr', models.IntegerField(default=0)),
                ('fouthmthr', models.IntegerField(default=0)),
                ('fifthmthr', models.IntegerField(default=0)),
                ('sixthmthr', models.IntegerField(default=0)),
                ('totalr', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
