# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190215_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='backofice',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilemake',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
