"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
os.environ['DJANGO_SETTINGS_MODULE'] = 'mysite.settings'


if os.name == 'nt':
    import platform
    OSGEO4W = r"C:\OSGeo4W"
    if '64' in platform.architecture()[0]:
        OSGEO4W += "64"
    assert os.path.isdir(OSGEO4W), "Directory does not exist: " + OSGEO4W
    os.environ['OSGEO4W_ROOT'] = OSGEO4W
    #os.environ['GDAL_DATA'] = "C:\Program Files\GDAL\gdal-data" 
    os.environ['PROJ_LIB'] = OSGEO4W + r"\share\proj"
    #GDAL_LIBRARY_PATH = r'C:\OSGeo4W64\bin\gdal204'
    os.environ['PATH'] = OSGEO4W + r"\bin;" + os.environ['PATH']

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'mob_we*$0e2cpfq^0jey+wakxnzl&46%6v=tov)0p+&0!4(4!b'

# SECURITY WARNING: don't run with debug turned on in production!

# import socket

# if socket.gethostname() == "server_name":
#     DEBUG = False
#     ALLOWED_HOSTS = ["www.obgmycompany.com",]
#     ...
# else:
#     DEBUG = True
#     ALLOWED_HOSTS = ["localhost", "127.0.0.1",]


DEFAULT_AUTO_FIELD='django.db.models.AutoField'

DEBUG = True

# DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', 'oamsuy06.pythonanywhere.com','www.obgmycompany.com', 'www.vitabutanzania.com']
SERIALIZATION_MODULES = {
    "geojson": "django.contrib.gis.serializers.geojson", 
 }

# Application definition

INSTALLED_APPS = [
    'accounts',
    'home',
    'himaya',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'django.contrib.sitemaps',
    'django.contrib.gis',
    'leaflet',
    'django.contrib.gis.db.models',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# # local postgres
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'test2',
        'USER': 'postgres',
        'HOST': 'localhost',
        'PASSWORD': 'Savioury9',
        'PORT': '5432',
    }
}

# live postgres
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.contrib.gis.db.backends.postgis',
#         'NAME': 'mygis',
#         'USER': 'obmsuya',
#         'PASSWORD': 'Savioury9',
#         'HOST': 'oamsuy06-2358.postgres.pythonanywhere-services.com',
#         'PORT': '12358',
#     }
# }








# CORS_REPLACE_HTTPS_REFERER = True
# HOT_SCHEME = "https://"
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTOCOL', 'https')
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE=True
# CRSF_COOKIE_SECURE = True
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_SECONDS = 1000000
# SECURE_FRAME_DENY = True



# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# changed

LOGIN_REDIRECT_URL = '/home/authors'

LOGOUT_REDIRECT_URL = '/account/entry/'



STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'static', 'static_root')


STATICFILES_DIRS = (
  os.path.join(os.path.dirname(BASE_DIR), 'static', 'static_dirs'),

)

#MEDIA_ROOT =  os.path.join(BASE_DIR, 'mysite/media')
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'static', 'media')


MEDIA_URL = '/media/'


# AWS_ACCESS_KEY_ID = 'AKIAIGCRUOY6E5QWAXDQ'
# AWS_SECRET_ACCESS_KEY = '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'
# AWS_STORAGE_BUCKET_NAME = 'www.obgmycompany.com'
# AWS_S3_FILE_OVERWRITE = False
# AWS_DEFAULT_ACL = None
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# AWS_S3_REGION_NAME = 'eu-west-2'
# AWS_S3_SIGNATURE_VERSION = "s3v4"
# AWS_S3_FILE_OVERWRITE = True
# AWS_FILE_EXPIRE = 200





# LOGIN_EXEMPT_URLS = (
#     r'^account/logout/$',
#     r'^account/register/$'
#     r'^account/reset-password/$',
#     r'^account/reset-password/done/$',
#     r'^account/password_reset_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
#     r'^account/reset-password/complete/$',

# )





# EMAIL_HOST = 'localhost'
# EMAIL_PORT = 1025

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'oamsuy06'
EMAIL_HOST_PASSWORD = 'Savioury9'