# Generated by Django 3.2.7 on 2021-10-04 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Paymentdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Post4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('region', models.CharField(default='', max_length=100)),
                ('Proffession', models.CharField(default='', max_length=100)),
                ('book', models.CharField(default='', max_length=250)),
                ('subtitle', models.CharField(default='', max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('Jina', models.CharField(default='', max_length=100)),
                ('Simu', models.IntegerField(default=0)),
                ('Tukusaidiaje', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Students Request',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=200)),
                ('bookname', models.CharField(blank=True, default='', max_length=220)),
                ('booklink', models.CharField(blank=True, default='', max_length=220)),
                ('bookimage', models.ImageField(default='default.jpg', upload_to='media')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subtitle', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='media')),
                ('image_author', models.ImageField(default='default.jpg', upload_to='media')),
                ('image_index', models.ImageField(default='default.jpg', upload_to='media')),
                ('videofile', models.FileField(default='default.mp4', null=True, upload_to='media', verbose_name='')),
                ('author', models.CharField(default='', max_length=200)),
                ('author_description', models.TextField(default='')),
                ('price', models.IntegerField(default=0)),
                ('tigopesa', models.IntegerField(blank=True, default=0)),
                ('mpesa', models.IntegerField(blank=True, default=0)),
                ('airtel', models.IntegerField(blank=True, default=0)),
                ('halotel', models.IntegerField(blank=True, default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
                ('paymentdetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.paymentdetail')),
            ],
            options={
                'verbose_name_plural': 'Item',
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
