# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190215_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='subtitle',
            field=models.CharField(default='', max_length=120),
        ),
    ]
