# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190227_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
