# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 07:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_auto_20190227_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('item', models.CharField(default='', max_length=120)),
                ('tigopesa', models.IntegerField(blank=True, default=0)),
                ('mpesa', models.IntegerField(blank=True, default=0)),
                ('airtel', models.IntegerField(blank=True, default=0)),
                ('halotel', models.IntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('item', models.CharField(default='', max_length=120)),
                ('tigopesa', models.IntegerField(blank=True, default=0)),
                ('mpesa', models.IntegerField(blank=True, default=0)),
                ('airtel', models.IntegerField(blank=True, default=0)),
                ('halotel', models.IntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
