# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_donate_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='airtel',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='halotel',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='mpesa',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='tigopesa',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
