# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190301_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='airtel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='halotel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='mpesa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='tigopesa',
            field=models.IntegerField(default=0),
        ),
    ]
