# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190301_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='airtel',
        ),
        migrations.RemoveField(
            model_name='item',
            name='halotel',
        ),
        migrations.RemoveField(
            model_name='item',
            name='mpesa',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tigopesa',
        ),
    ]
