# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190301_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('item', models.CharField(default='', max_length=120)),
                ('tigopesa', models.IntegerField(blank=True, default=0)),
                ('mpesa', models.IntegerField(blank=True, default=0)),
                ('airtel', models.IntegerField(blank=True, default=0)),
                ('halotel', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
