# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 08:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_paymentdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='paymentdetail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Paymentdetail'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
