# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190301_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='donate',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
