# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20190301_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post4',
            old_name='subject',
            new_name='book',
        ),
    ]
