# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190305_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post4',
            name='book',
            field=models.CharField(default='', max_length=250),
        ),
    ]
