# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-21 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20190305_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_index',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field'),
        ),
    ]
