# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-21 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_item_image_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='item',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_author',
            field=models.ImageField(default='default.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_index',
            field=models.ImageField(default='default.jpg', upload_to='media'),
        ),
    ]
