# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-22 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190321_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='airtel',
        ),
        migrations.RemoveField(
            model_name='item',
            name='author',
        ),
        migrations.RemoveField(
            model_name='item',
            name='author_description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='halotel',
        ),
        migrations.RemoveField(
            model_name='item',
            name='mpesa',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tigopesa',
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='airtel',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='author_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='halotel',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='mpesa',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='tigopesa',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
