# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-22 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20190322_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='author',
        ),
    ]
