# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-22 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_paymentdetail_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
