# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-22 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20190322_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
    ]
