# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-22 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_paymentdetail_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='airtel',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='author',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='author_description',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='halotel',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='mpesa',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='tigopesa',
        ),
        migrations.AddField(
            model_name='item',
            name='airtel',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='author_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='halotel',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='mpesa',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='tigopesa',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
