# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-23 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20190322_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='author_description',
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='author_description',
            field=models.TextField(default=''),
        ),
    ]
