# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-23 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20190323_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='videofile',
            field=models.FileField(default='default.mp4', null=True, upload_to='media', verbose_name=''),
        ),
    ]
