# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-11 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20190323_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='book',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
