# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-19 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_post_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='book',
        ),
        migrations.RemoveField(
            model_name='post',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='width_field',
        ),
        migrations.AddField(
            model_name='post',
            name='bookactivator',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='post',
            name='bookname',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
    ]
