# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-19 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20190419_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bookactivator',
            new_name='booklink',
        ),
    ]
