# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-20 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20190419_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='post',
        ),
    ]
