# Generated by Django 3.2.4 on 2021-06-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_friend_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookimage',
            field=models.ImageField(default='default.jpg', upload_to='media'),
        ),
    ]
