# Generated by Django 3.2.7 on 2021-10-04 12:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Const_Winners_Geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_nam', models.CharField(blank=True, max_length=50, null=True)),
                ('district_n', models.CharField(blank=True, max_length=50, null=True)),
                ('const', models.CharField(blank=True, max_length=50, null=True)),
                ('constid', models.BigIntegerField(blank=True, null=True)),
                ('concilid', models.BigIntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('votes', models.BigIntegerField(blank=True, null=True)),
                ('chama_id', models.SmallIntegerField(blank=True, null=True)),
                ('const_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'const_winners_geo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Constituents',
            fields=[
                ('region_nam', models.CharField(blank=True, max_length=50, null=True)),
                ('district_n', models.CharField(blank=True, max_length=50, null=True)),
                ('const', models.CharField(blank=True, max_length=50, null=True)),
                ('constid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('concilid', models.SmallIntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'constituents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConstVotes',
            fields=[
                ('candidate_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('chama_id', models.SmallIntegerField()),
                ('votes', models.BigIntegerField()),
                ('candidate', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'const_votes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('region_nam', models.CharField(blank=True, max_length=50, null=True)),
                ('district_n', models.CharField(blank=True, max_length=50, null=True)),
                ('distid', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'districts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pres_Const_Winners_Geo',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('region_nam', models.CharField(blank=True, max_length=50, null=True)),
                ('district_n', models.CharField(blank=True, max_length=50, null=True)),
                ('const', models.CharField(blank=True, max_length=50, null=True)),
                ('constid', models.BigIntegerField()),
                ('concilid', models.SmallIntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('chama_id', models.SmallIntegerField()),
                ('votes', models.BigIntegerField()),
                ('const_id', models.BigIntegerField()),
                ('cand_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pres_winners_geo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PresVotesConst',
            fields=[
                ('vote_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('const_id', models.BigIntegerField()),
                ('chama_id', models.SmallIntegerField()),
                ('votes', models.BigIntegerField()),
                ('cand_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pres_votes_const',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regcentre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=32737)),
                ('n_op', models.CharField(blank=True, max_length=13, null=True)),
                ('ward', models.CharField(blank=True, max_length=254, null=True)),
                ('reg_centre', models.CharField(blank=True, max_length=254, null=True)),
                ('reg_id', models.BigIntegerField(blank=True, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('shrtname', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'RegCentre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regional_Votes_Geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_nam', models.CharField(blank=True, max_length=50, null=True)),
                ('regionid', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('zone', models.CharField(blank=True, max_length=250, null=True)),
                ('zoneid', models.BigIntegerField(blank=True, null=True)),
                ('leveltypei', models.BigIntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('votes', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'regional_votes_geo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegionalVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('votes', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'regional_votes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('region_nam', models.CharField(blank=True, max_length=50, null=True)),
                ('regionid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('zone', models.CharField(blank=True, max_length=250, null=True)),
                ('zoneid', models.SmallIntegerField(blank=True, null=True)),
                ('leveltypei', models.SmallIntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'regions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tanzania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'tanzania',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4210)),
                ('regname', models.CharField(blank=True, max_length=30, null=True)),
                ('ward_name', models.CharField(blank=True, max_length=30, null=True)),
                ('street', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'Village',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wards',
            fields=[
                ('region_nam', models.CharField(blank=True, max_length=50, null=True)),
                ('district_n', models.CharField(blank=True, max_length=50, null=True)),
                ('ward_name', models.CharField(blank=True, max_length=50, null=True)),
                ('const', models.CharField(blank=True, max_length=50, null=True)),
                ('wardid', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('constid', models.BigIntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'wards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wards_Winners_Geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_nam', models.CharField(blank=True, max_length=50, null=True)),
                ('district_n', models.CharField(blank=True, max_length=50, null=True)),
                ('ward_name', models.CharField(blank=True, max_length=50, null=True)),
                ('const', models.CharField(blank=True, max_length=50, null=True)),
                ('wardid', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('constid', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('votes', models.BigIntegerField(blank=True, null=True)),
                ('chama_id', models.SmallIntegerField(blank=True, null=True)),
                ('ward_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wards_winners_geo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WardVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.BigIntegerField()),
                ('ward_id', models.BigIntegerField()),
                ('chama_id', models.SmallIntegerField(blank=True, null=True)),
                ('votes', models.BigIntegerField(blank=True, null=True)),
                ('candidate', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ward_votes',
                'managed': False,
            },
        ),
    ]
